version: "3.7"
services:
  app:
    build: .
    image: social-network
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: admin
      PGDATABASE: postgres
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      #POSTGRES_DB: po
      PGDATA: var/lib/postgresql/data/pgdata
volumes:
  pgdata:
